# Generated by Django 6.0.4 on 2026-04-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriterioDoacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("REQ", "Requisito Básico"),
                            ("IMP_TEMP", "Impedimento temporário"),
                            ("IMP_DEF", "Impedimento definitivo"),
                        ],
                        default="REQ",
                        max_length=10,
                    ),
                ),
                (
                    "saiba_mais",
                    models.TextField(
                        blank=True,
                        help_text="Informações detalhadas sobre este critério.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério de Doação",
                "verbose_name_plural": "Critérios de Doação",
            },
        ),
        migrations.CreateModel(
            name="Doador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="ID do usuário no Gateway", unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True, null=True, upload_to="perfil_doadores/"
                    ),
                ),
                (
                    "tipo_sanguineo",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Tipo Sanguíneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doador",
                "verbose_name_plural": "Doadores",
            },
        ),
        migrations.CreateModel(
            name="LocalDoacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("endereco", models.CharField(max_length=200)),
                ("cidade", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Local de Doação",
                "verbose_name_plural": "Locais de Doação",
            },
        ),
        migrations.CreateModel(
            name="DemonstracaoInteresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solicitacao_id",
                    models.IntegerField(verbose_name="ID da Solicitação Externa"),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        help_text="Upload do documento ou exame comprobatório",
                        null=True,
                        upload_to="comprovantes/%Y/%m/",
                    ),
                ),
                (
                    "doador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interesses",
                        to="gestao_doadores.doador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demonstração de Interesse",
                "verbose_name_plural": "Demonstrações de Interesse",
            },
        ),
    ]
