# Generated by Django 6.0.4 on 2026-04-30 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_doadores", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocalDoacao",
        ),
        migrations.AlterModelOptions(
            name="registrardoacao",
            options={
                "verbose_name": "Registro de Doação",
                "verbose_name_plural": "Registros de Doação",
            },
        ),
        migrations.AlterField(
            model_name="registrardoacao",
            name="doador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="gestao_doadores.doador",
            ),
        ),
    ]
