# Generated by Django 6.0.4 on 2026-04-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestao_doadores",
            "0002_delete_localdoacao_alter_registrardoacao_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="registrardoacao",
            table="gestao_doadores_registrardoacao",
        ),
    ]
