# Generated by Django 6.0.4 on 2026-04-30 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_pacientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="idade",
        ),
        migrations.AddField(
            model_name="paciente",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to="perfil_pacientes/"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="user_id",
            field=models.IntegerField(
                default=0, help_text="ID do usuário no Gateway", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="tipo_sanguineo",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="SolicitacaoDoacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=255)),
                ("tipo_sanguineo_necessario", models.CharField(max_length=3)),
                ("urgente", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_pacientes.paciente",
                    ),
                ),
            ],
        ),
    ]
